### ISSUE TITLE
Progress bars/indicators? Keyboard interactions?

### ISSUE THREAD

**Issue by polarathene** [killercup/quicli#22] opened 2018-01-26 04:37 UTC
How would you go about introducing progress visuals(common to see something like `[=====---------]49%`) or busy indicators(I've seen a project for this, maybe it was in zsh but should be portable to general CLI output from Rust).

I recall using a CLI app, Hashcat last year that would show several lines of what was going on followed by many lines of status of the computation that was updated and below that were some interactivity options along with shortcut keys that could pause/stop/save/etc the computation. 

I guess these would both be a better story as async support develops further in the year, but a neat feature for quicli to be able to offer easily setting up? Item (key, description/label, function to call), view(list of items arranged horizontally I guess?)... or is that going too far into TUI land?

Let me know if you'd like me to split the two features into separate issues.

**Comment by killercup** [comment] 2018-01-26 10:39
Yeah, we'd need to do some kind of async event handling to do progress indicators right, but I think we can provide some simple wrappers around that.

> Let me know if you'd like me to split the two features into separate issues.

We actually already have #10 and #11 :) I'll close this issue as a duplicate of these.

**Closed by killercup** 2018-01-26 10:39 UTC
